# Server
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/securevault?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=udhaya123123@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=SecureVaultJWTSecretKey2024SuperLongSecretKeyForHS512AlgorithmMustBe64BytesLong!
app.jwt.expiration=86400000

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# File Storage Path (files stored encrypted on disk)
app.file.storage.path=./encrypted-files

# CORS
app.cors.allowed-origins=http://localhost:3000

# Logging
logging.level.com.securevault=INFO
logging.level.org.springframework.security=WARN