# Server
server.port=8080

# MySQL Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=SecureVaultJWTSecretKey2024SuperLongSecretKeyForHS512AlgorithmMustBe64BytesLong!
app.jwt.expiration=86400000

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# File Storage Path (files stored encrypted on disk)
app.file.storage.path=./encrypted-files

# CORS
app.cors.allowed-origins=http://localhost:3000

# Logging
logging.level.com.securevault=INFO
logging.level.org.springframework.security=WARN